Repository centreon/centreon-collect, pull requests merged in 2024-08, with the labels that each got.

#1547 fix(gorgone/mbi): rebuilding centiles truncates mod_bi_metrichourlyvalue
  gorgone/gorgone/modules/centreon/mbi/etl/perfdata/main.pm
Labels: gorgone

#1546 fix(gorgone/mbi): add weekly and monthly centiles partitioning
  gorgone/gorgone/modules/centreon/mbi/etl/perfdata/main.pm
Labels: gorgone

#1522 fix(gorgone): Add missing centengine report part to centreon-storage database
  .github/docker/Dockerfile.gorgone-testing-alma9
  .github/docker/Dockerfile.gorgone-testing-bookworm
  .github/docker/Dockerfile.gorgone-testing-bullseye
  .github/docker/Dockerfile.gorgone-testing-jammy
  .github/workflows/gorgone.yml
  gorgone/docs/modules/centreon/statistics.md
  gorgone/gorgone/modules/centreon/statistics/class.pm
  gorgone/packaging/centreon-gorgone.yaml
  gorgone/tests/robot/config/actions.yaml
  gorgone/tests/robot/config/gorgone_core_central.yaml
  gorgone/tests/robot/config/push_central_config.yaml
  gorgone/tests/robot/config/statistics.yaml
  gorgone/tests/robot/resources/LogResearch.py
  gorgone/tests/robot/resources/import.resource
  gorgone/tests/robot/resources/resources.resource
  gorgone/tests/robot/tests/centreon/centenginestats
  gorgone/tests/robot/tests/centreon/statistics.robot
  gorgone/tests/robot/tests/core/httpserver.robot
  gorgone/tests/robot/tests/core/pullwss.robot
  gorgone/tests/robot/tests/start_stop/start_stop.robot
Labels: gorgone

#1620 chore(deps): absorb 24.08 dependabot GitHub Actions updates
  .github/workflows/centreon-collect.yml
  .github/workflows/docker-builder.yml
  .github/workflows/docker-gorgone-testing.yml
  .github/workflows/gorgone.yml
  .github/workflows/lua-curl.yml
  .github/workflows/package-collect.yml
  .github/workflows/robot-test.yml
  .github/workflows/windows-agent.yml
Labels: dependencies, gha

#1618 fix(ci): add gorgone to collect component list (#1612)
  .github/actions/release/action.yml
Labels: backport

#1633 chore(ci): enable shellcheck and integrate check-status workflow (#1579)
  .github/workflows/actionlint.yml
  .github/workflows/check-status.yml
  gorgone/packaging/centreon-audit.yaml
Labels: backport

#1631 chore(ci): enable shellcheck and integrate check-status workflow (#1579)
  .github/workflows/actionlint.yml
  .github/workflows/check-status.yml
  gorgone/packaging/centreon-audit.yaml
Labels: backport

#1630 chore(ci): enable shellcheck and integrate check-status workflow (#1579)
  .github/workflows/actionlint.yml
  .github/workflows/check-status.yml
  .github/workflows/package-collect.yml
Labels: backport

#1615 fix(ci): add gorgone to collect component list (#1612)
  .github/actions/release/action.yml
Labels: backport

#1616 fix(ci): add gorgone to collect component list (#1612)
  .github/actions/release/action.yml
Labels: backport

#1553 [dev-24.04.x] [gorgone] Fix column length for MBI (MON-143654)
  gorgone/gorgone/modules/centreon/mbi/libs/bi/BIMetric.pm
Labels: gorgone

#1554 [dev-23.10.x] [gorgone] Fix column length for MBI (MON-143655)
  gorgone/gorgone/modules/centreon/mbi/libs/bi/BIMetric.pm
Labels: gorgone
